[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "phd-conformal-p2p"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "marimo>=0.20.2",
    "polars>=1.38.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.4",
]

[tool.hatch.build.targets.wheel]
packages = ["dslib"]

