[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "phd-conformal-p2p"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hydra-core>=1.3.2",
    "loguru>=0.7.3",
    "marimo>=0.20.2",
    "mlflow>=3.10.0",
    "pandera>=0.29.0",
    "polars>=1.38.1",
    "python-dotenv>=1.2.2",
    "scikit-learn>=1.8.0",
    "xgboost>=3.2.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.4",
]

[tool.hatch.build.targets.wheel]
packages = ["dslib"]

